[package]
name = "fftw_learn"
version = "0.1.0"
authors = ["liang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fftw = "0.6.2"
csv = "1.1.3"